Leets-Official/Fling-BE

build.gradle, src/main/java/com/fling/fllingbe/global/config/WebSecurityConfig.java, src/main/java/com/fling/fllingbe/global/swagger/SwaggerConfig.java
- API의 명세서를 작성하기 위한 Swagger 구축하였습니다.
- 개발 및 테스트를 위해 Swagger UI에 접근할 수 있도록 WebSecurity에 해당 주소를 추가하였습니다.
<br>
<br>
<br>
- Swagger를 이용한 API 명세서 생성 및 Swagger UI 접근 설정 완료
- WebSecurity에 Swagger UI 주소 추가 완료
<br>
close #3
=> [feat] #6 Swagger 구축

src/main/java/com/fling/fllingbe/domain/item/application/DecoItemService.java, src/main/java/com/fling/fllingbe/domain/item/domain/DecoItem.java, src/main/java/com/fling/fllingbe/domain/item/domain/DecoType.java, src/main/java/com/fling/fllingbe/domain/item/domain/FlowerItem.java, src/main/java/com/fling/fllingbe/domain/item/domain/FlowerType.java, src/main/java/com/fling/fllingbe/domain/item/dto/DecoItemResponse.java, src/main/java/com/fling/fllingbe/domain/item/presentation/DecoItemController.java, src/main/java/com/fling/fllingbe/domain/item/repository/DecoItemRepository.java, src/main/java/com/fling/fllingbe/domain/item/repository/DecoTypeRepository.java
<br>
userid를 통해 데코아이템을 가져오는 기능을 추가했습니다.
<br>
로그인과 토큰 기능이 구현되어 있지 않아 pathvariable을 이용하여 컨트롤러를 구현하였습니다. 추후 수정 예정입니다.
<br>
해당 없습니다.
<br>
userid를 통해 데코아이템을 추출하는 로직구현
close #13
=> [feat] #14 데코 아이템 가져오기 기능 추가

build.gradle, src/main/java/com/fling/fllingbe/domain/user/application/UserService.java, src/main/java/com/fling/fllingbe/domain/user/domain/User.java, src/main/java/com/fling/fllingbe/domain/user/dto/UserRequest.java, src/main/java/com/fling/fllingbe/domain/user/dto/UserResponse.java, src/main/java/com/fling/fllingbe/domain/user/presentation/UserController.java, src/main/java/com/fling/fllingbe/domain/user/repository/UserRepository.java, src/main/resources/application.properties
로그인 회원가입 기능을 제작하였습니다.
<br>
로그인과 회원가입이 가능하며,
access토큰을 반환합니다.
이후 카카오톡 로그인 기능과 리프레쉬 토큰 로직을 추가하겠습니다.
=> [feat] #17 로그인 회원가입 제작

src/main/java/com/fling/fllingbe/domain/bouquet/application/BouquetService.java, src/main/java/com/fling/fllingbe/domain/bouquet/dto/CreateBouquetRequest.java, src/main/java/com/fling/fllingbe/domain/bouquet/presentation/BouquetController.java, src/main/resources/application.properties
<br>
최초 꽃다발을 생성하는 기능을 추가하였습니다
<br>
아직 토큰에서 유저를 얻어오는 로직이 구현되지 않아 pathvariable을 통해 테스트가 이루어졌습니다. 추후 수정할 예정입니다.
<br>
<br>
유저가 선택한 리본과 포장지로 최초 꽃다발을 생성하는 로직 구현 
close #22
=> [feat] #23 꽃다발 생성 기능 추가

src/main/java/com/fling/fllingbe/domain/item/presentation/CardItemController.java, src/main/java/com/fling/fllingbe/domain/user/application/UserService.java, src/main/java/com/fling/fllingbe/domain/user/dto/TestUserRequest.java, src/main/java/com/fling/fllingbe/domain/user/presentation/UserController.java, src/main/resources/application.properties
카카오톡 로그인 개발하였습니다.
<br>
<br>
개발시에는 /user/test-login   /user/test-register 사용하시면 됩니다.
<br>
=> [Feat] #28 카카오톡 로그인 개발

src/main/java/com/fling/fllingbe/domain/bouquet/application/BouquetService.java, src/main/java/com/fling/fllingbe/domain/bouquet/domain/Bouquet.java, src/main/java/com/fling/fllingbe/domain/bouquet/dto/BouquetDesign.java, src/main/java/com/fling/fllingbe/domain/bouquet/dto/BouquetInfo.java, src/main/java/com/fling/fllingbe/domain/bouquet/dto/GetBouquetResponse.java, src/main/java/com/fling/fllingbe/domain/bouquet/presentation/BouquetController.java, src/main/java/com/fling/fllingbe/domain/flower/domain/Flower.java, src/main/java/com/fling/fllingbe/domain/flower/dto/FlowerInfo.java, src/main/java/com/fling/fllingbe/domain/flower/repository/FlowerRepository.java, src/main/java/com/fling/fllingbe/domain/item/application/CardItemService.java, src/main/java/com/fling/fllingbe/domain/item/application/FlowerItemService.java, src/main/java/com/fling/fllingbe/domain/item/presentation/CardItemController.java, src/main/java/com/fling/fllingbe/domain/user/application/UserService.java, src/main/java/com/fling/fllingbe/domain/user/dto/TestUserRequest.java, src/main/java/com/fling/fllingbe/domain/user/presentation/UserController.java, src/main/java/com/fling/fllingbe/global/shared/domain/BaseTimeEntity.java, src/main/resources/application.properties
<br>
유저가 가지고 있는 꽃다발을 가지고 오는 기능을 추가하였습니다.
<br>
1. 테스트 중 모든 create_at 필드 값이 null로 생성되는 오류를 발견하였습니다.
baseTimeEntity에 @CreationTimestamp 어노테이션을 추가하여 해결하였습니다.
2. 현재 postman으로 테스트 시 Authrozation 헤더를 직접 추가하여 테스트 하는 경우에는 문제가 발생하지 않으나 Authorization 탭에서 토큰을 추가할 경우 "message": "Illegal base64url character: ' '", 오류가 발생하는 현상이 있습니다. 담당자 분과 문제 확인 후 수정하도록 하겠습니다.
<br>
<br>
유저가 보유한 꽃다발을 가져오는 로직 구현
꽃다발, 꽃 생성시 db에 create_at이 null로 저장되는 현상 수정 
close #24
=> [feat] #29 꽃다발 가져오기 기능 추가

build.gradle, src/main/java/com/fling/fllingbe/domain/user/application/UserService.java, src/main/java/com/fling/fllingbe/domain/user/dto/RefreshRequest.java, src/main/java/com/fling/fllingbe/domain/user/dto/UserResponse.java, src/main/java/com/fling/fllingbe/domain/user/presentation/UserController.java, src/main/java/com/fling/fllingbe/global/jwt/JwtProvider.java, src/main/java/com/fling/fllingbe/global/redis/RedisConfig.java, src/main/resources/application.properties
레디스 적용과 리프레시 토큰 생성 개발하였습니다.
<br>
<br>
=> [feat] #31 레디스 적용과 리프레시 토큰 생성 개발

src/main/java/com/fling/fllingbe/domain/flower/application/FlowerService.java, src/main/java/com/fling/fllingbe/domain/flower/presentation/FlowerController.java, src/main/java/com/fling/fllingbe/domain/item/application/CardItemService.java, src/main/java/com/fling/fllingbe/domain/item/application/DecoItemService.java, src/main/java/com/fling/fllingbe/domain/item/application/FlowerItemService.java, src/main/java/com/fling/fllingbe/domain/item/presentation/CardItemController.java, src/main/java/com/fling/fllingbe/domain/item/presentation/DecoItemController.java, src/main/java/com/fling/fllingbe/domain/item/presentation/FlowerItemController.java
<br>
기존 path variable을 사용한 코드에서 토큰을 이용하여 유저를 구분하도록 코드를 변경하였습니다.
<br>
<br>
<br>
유저를 UUID에서 토큰을 이용하여 userEmail을 추출하여 구분하도록 코드를 수정
close #19
=> [feat] #32 토큰을 이용하여 유저를 구분하는 기능 추가

src/main/java/com/fling/fllingbe/domain/bouquet/application/BouquetService.java, src/main/java/com/fling/fllingbe/domain/bouquet/dto/BouquetInfo.java, src/main/java/com/fling/fllingbe/domain/flower/application/FlowerService.java, src/main/java/com/fling/fllingbe/domain/flower/dto/ReceivedFlower.java, src/main/java/com/fling/fllingbe/domain/flower/dto/SentFlower.java, src/main/java/com/fling/fllingbe/domain/flower/presentation/FlowerController.java, src/main/java/com/fling/fllingbe/domain/flower/repository/FlowerRepository.java
<br>
보낸편지, 받은 편지를 출력하는 기능을 추가하였습니다.
<br>
없습니다.
<br>
<br>
보낸 편지와 받는 편지를 출력하는 로직 구현
close #33
=> [feat] #34 보낸편지,받은편지 기능 추가

src/main/java/com/fling/fllingbe/domain/coin/application/CoinService.java, src/main/java/com/fling/fllingbe/domain/coin/domain/Coin.java, src/main/java/com/fling/fllingbe/domain/coin/dto/CoinRequest.java, src/main/java/com/fling/fllingbe/domain/coin/exception/CoinNotFoundException.java, src/main/java/com/fling/fllingbe/domain/coin/presentation/CoinController.java, src/main/java/com/fling/fllingbe/domain/coin/repository/CoinRepository.java, src/main/java/com/fling/fllingbe/domain/user/application/UserService.java, src/main/java/com/fling/fllingbe/global/error/ErrorCode.java
- 코인 업데이트 API를 추가하였습니다.
<br>
<br>
<br>
- POST /coin
Request
```
{
"coin": -300
}
```
Response
```
{
"message": "코인 업데이트가 성공했습니다."
}
```
<br>
close #9
=> [feat] #37 코인 업데이트 기능 추가

src/main/java/com/fling/fllingbe/domain/flower/application/FlowerService.java, src/main/java/com/fling/fllingbe/domain/flower/dto/GetLetter.java, src/main/java/com/fling/fllingbe/domain/flower/presentation/FlowerController.java, src/main/java/com/fling/fllingbe/domain/item/application/CardItemService.java, src/main/java/com/fling/fllingbe/domain/item/application/DecoItemService.java, src/main/java/com/fling/fllingbe/domain/item/application/FlowerItemService.java, src/main/java/com/fling/fllingbe/domain/item/dto/GetItemById.java, src/main/java/com/fling/fllingbe/domain/item/presentation/CardItemController.java, src/main/java/com/fling/fllingbe/domain/item/presentation/DecoItemController.java, src/main/java/com/fling/fllingbe/domain/item/presentation/FlowerItemController.java
<br>
편지 읽기 기능을 추가하였습니다
<br>
없습니다
<br>
<br>
꽃 id를 통해 편지를 읽는 기능 추가
close #45
=> [feat] #46 편지 읽기 기능 추가

build.gradle, src/main/java/com/fling/fllingbe/domain/user/presentation/UserController.java, src/main/java/com/fling/fllingbe/global/jwt/JwtProvider.java, src/main/java/com/fling/fllingbe/global/redis/RedisConfig.java
토큰 재발급시 리프레시 토큰도 발급하는 문제를 수정하였습니다.
<br>
<br>
<br>
로그인 api메소드를 POST -> GET으로 변경하였습니다.
=> [fix] #48 토큰 재발급시 리프레시 토큰도 발급하는 문제 해결

src/main/java/com/fling/fllingbe/domain/user/presentation/HealthCheckController.java
- https 적용을 위해 로드밸런서 대상 그룹의 인스턴스 상태를 확인할 api를 생성했습니다.
- swagger에도 api 설명을 추가했습니다.
<br>
<br>
<br>
<br>
close #49
=> [feat] #50 HealthCheckController 추가 완료

src/main/java/com/fling/fllingbe/global/redis/RedisConfig.java
=> [hotfix] #51 레디스 빈 주입 오류 해결

src/main/java/com/fling/fllingbe/domain/user/application/UserService.java, src/main/java/com/fling/fllingbe/domain/user/domain/User.java, src/main/java/com/fling/fllingbe/domain/user/dto/CongratulateeDto.java, src/main/java/com/fling/fllingbe/domain/user/dto/NicknameRequest.java, src/main/java/com/fling/fllingbe/domain/user/dto/UserResponse.java, src/main/java/com/fling/fllingbe/domain/user/presentation/UserController.java, src/main/java/com/fling/fllingbe/domain/user/repository/UserRepository.java, src/main/java/com/fling/fllingbe/global/redis/RedisConfig.java, src/main/resources/application.properties
꽃 받는 사람 정보api와 유저 패치과 삭제 추가함.
d-day나 설명글과 같은 꽃 받는 사람의 정보들을 수정하고, 조회할수 있는 api를 개발하였습니다.
추가로 유저 닉네임 수정과 유저 삭제 api를 제작하였습니다.
<br>
<br>
<br>
=> [feat] #54 꽃 받는 사람 정보api와 유저 패치과 삭제 추가

src/main/java/com/fling/fllingbe/domain/user/presentation/UserController.java
로그인과 리프레시 api 메소드 post로 변경
<br>
<br>
<br>
=> [fix] #57 로그인과 리프레시 api 메소드 post로 변경

src/main/java/com/fling/fllingbe/domain/flower/application/FlowerService.java, src/main/java/com/fling/fllingbe/domain/item/application/CardItemService.java, src/main/java/com/fling/fllingbe/domain/item/application/DecoItemService.java, src/main/java/com/fling/fllingbe/domain/item/application/FlowerItemService.java
<br>
기본 아이템의 수량을 0이 아닌 -1 로 수정하였습니다
<br>
꽃다발 수정 시 아이템에 owned 가 설정되지 않던 부분을 발견하여 수정하였습니다.
<br>
해당사항 없습니다.
<br>
유저 생성시 기본아이템 수량을 -1 로 변경
꽃다발 수정시 아이템에 owned가 설정되도록 변경
close #59
=> [fix] #60 createDafaultFloweritem 수정

src/main/java/com/fling/fllingbe/domain/item/domain/DecoItem.java, src/main/java/com/fling/fllingbe/domain/item/exception/DecoItemNotFoundException.java, src/main/java/com/fling/fllingbe/domain/item/exception/DecoTypeNotFoundException.java, src/main/java/com/fling/fllingbe/domain/store/application/StoreService.java, src/main/java/com/fling/fllingbe/domain/store/dto/DecoPurchaseRequest.java, src/main/java/com/fling/fllingbe/domain/store/presentation/StoreController.java, src/main/java/com/fling/fllingbe/global/error/ErrorCode.java
- 상점 데코 구매 API 구현합니다. 
<br>
<br>
<br>
- 상점 데코 구매 API를 구현합니다. 
- POST /store/deco으로 값을 요청합니다. 
- owned를 false에서 true로 갱신합니다.
- 해당 데코의 가격만큼 coin을 차감합니다.
- 요청값과 응답값은 다음과 같습니다. 
Request 
```json
{
"method": "POST",
"path": "/store/deco",
"headers": {
"Authorization": "Bearer {token}"
},
"body": {
"decoId": "Long"
}
}
```
성공적인 응답(Response)
```json
{
"status": 200,
"statusText": "OK",
"headers": {
"Content-Type": "application/json"
},
"body": {
"message": "데코 구매를 성공했습니다."
}
}
```
에러 응답(Response)
```json
{
"status": 400,
"statusText": "BAD_REQUEST",
"body": {
"message": "데코 구매를 실패했습니다."
}
}
```
<br>
close #41
=> [feat] #63 상점 데코 구매 api 구현

src/main/java/com/fling/fllingbe/domain/item/application/CardItemService.java, src/main/java/com/fling/fllingbe/domain/store/application/StoreService.java, src/main/java/com/fling/fllingbe/domain/store/dto/StoreResponse.java, src/main/java/com/fling/fllingbe/domain/store/presentation/StoreController.java
- 상점 아이템 가져오기 API 구현하였습니다.
- GET /store으로 값을 요청합니다.
<br>
<br>
<br>
<br>
close #65
=> [feat] #67 상점 아이템 가져오기 api 구현

src/main/java/com/fling/fllingbe/domain/item/application/CardItemService.java, src/main/java/com/fling/fllingbe/domain/item/application/DecoItemService.java, src/main/java/com/fling/fllingbe/domain/item/application/FlowerItemService.java, src/main/java/com/fling/fllingbe/domain/item/dto/AddCardItemRequest.java, src/main/java/com/fling/fllingbe/domain/item/dto/AddDecoItemRequest.java, src/main/java/com/fling/fllingbe/domain/item/dto/AddFlowerItemRequest.java, src/main/java/com/fling/fllingbe/domain/item/presentation/CardItemController.java, src/main/java/com/fling/fllingbe/domain/item/presentation/DecoItemController.java, src/main/java/com/fling/fllingbe/domain/item/presentation/FlowerItemController.java, src/main/java/com/fling/fllingbe/domain/user/application/UserService.java
<br>
아이템 데이터를 추가하는 api를 추가하였습니다.
<br>
test register에만 기본 아이템을 db에 저장하는 메서드가 적용된 것을 확인하여 해결하였습니다.
<br>
<br>
아이템 데이터를 추가하는 api 추가
user/register에 기본 아이템을 생성하는 메서드 추가
close #68
=> [feat] #69 아이템 추가 api 개발

src/main/java/com/fling/fllingbe/domain/bouquet/application/BouquetService.java, src/main/java/com/fling/fllingbe/domain/bouquet/dto/CreateBouquetRequest.java, src/main/java/com/fling/fllingbe/domain/bouquet/dto/GetBouquetResponse.java, src/main/java/com/fling/fllingbe/domain/user/application/UserService.java, src/main/java/com/fling/fllingbe/domain/user/domain/User.java, src/main/java/com/fling/fllingbe/domain/user/dto/CongratulateeDto.java, src/main/java/com/fling/fllingbe/domain/user/dto/UserInfoResponse.java, src/main/java/com/fling/fllingbe/domain/user/presentation/UserController.java, src/main/resources/application.properties
유저 정보 반환 api 개발함.
<br>
<br>
<br>
d-day 데이터 타입을 LocalDateTime -> String으로 변경
회원가입시 로그인 바로 진행으로 변경
=> [feat] #71 유저 정보 반환 api 개발

src/main/java/com/fling/fllingbe/domain/flower/application/FlowerService.java, src/main/java/com/fling/fllingbe/domain/flower/dto/SentFlower.java, src/main/java/com/fling/fllingbe/domain/flower/presentation/FlowerController.java
<br>
꽃 id 요청시 파라미터로 요청하도록 코드를 변경하였습니다.
<br>
받은 편지 api 에 flower type이 반환 되지 않은 현상을 발견하여 수정하였습니다.
<br>
<br>
flower contoller 수정
letter-sent dto 수정
close #73
=> [fix] #73 flower requset 형식 변경

build.gradle, src/main/java/com/fling/fllingbe/FlingApplication.java, src/main/java/com/fling/fllingbe/domain/item/repository/DecoItemRepository.java, src/main/java/com/fling/fllingbe/domain/store/application/StoreService.java, src/main/java/com/fling/fllingbe/domain/store/presentation/StoreController.java, src/main/java/com/fling/fllingbe/domain/user/application/UserService.java, src/main/java/com/fling/fllingbe/domain/user/exception/UserNotFoundException.java, src/main/java/com/fling/fllingbe/domain/user/repository/UserRepository.java, src/main/java/com/fling/fllingbe/global/dataSetting/RandomDecoSetter.java
매일 유저별 랜덤 데코 아이템 설정 개발
<br>
<br>
=> [feat] #77 매일 유저별 랜덤 데코 아이템 설정 개발

src/main/resources/application.properties
- 로딩 성능 최적화를 위해 gzip으로 압축하여 전송하는 기능을 구현했습니다.
- 500바이트 이상의 데이터를 압축하도록 구현했습니다.
<br>
<br>
<br>
<br>
close #78
=> [feat] #79 500바이트 이상의 데이터를 압축하는 기능 구현

src/main/java/com/fling/fllingbe/FlingApplication.java
=> Jenkins pr builder failed test6

src/main/java/com/fling/fllingbe/FlingApplication.java
=> Jenkins pr builder failed test7

src/main/java/com/fling/fllingbe/FlingApplication.java
=> Jenkins pr builder successful test2
